a = 15
b = 4
hasil_penjumlahan = a +b
hasil_pengurangan = a - b
hasil_perkalian = a* b
hasil_pembagian = a / b
hasil_pangkat = a ** b
hasil_modulus = a% b
print("Hasil dijumlahkan = " , hasil_penjumlahan)
print("Hasil pengurangan = " , hasil_pengurangan)
print("Hasil perkalian = " , hasil_perkalian)
print("Hasil pembagian = ", hasil_pembagian)
print("Hasil dipangkatkan a dan b = " , hasil_pangkat)
print("Hasil bagi sisa = " , hasil_modulus)